name: Nightly

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

jobs:
  upgrade:
    name: Upgrade & test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 15.x
    - id: upgrade
      name: Upgrade
      run: npx npm-check-updates --upgrade
    - name: Install
      run: npm install
    - name: Test
      run: npm run test
    - name: Build
      run: npm run build
    - if: failure()
      name: Create issue on failure
      uses: JasonEtco/create-an-issue@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        update_existing: true
        filename: .github/nightly_issue.md